version: '3.2'
services:
  web_server:
    image: nginx
    ports:
      - "80:80"
    deploy:
      mode: global  
    volumes:
      - type: bind
        source: ./nginx/simple_flask.conf
        target: /etc/nginx/conf.d/simple_flask.conf
    depends_on:
      - web_app
    networks:
      - my-network  
  web_app:
    build: ./app     
    ports:
      - "8000:8000"
    deploy:
      mode: global
    networks:
      - my-network
networks:
  my-network: