version: '3.2'
services:
  web_server:
    image: ngoctq/nginx-docker-test
    ports:
      - "80:80"
    deploy:
      mode: global  
    depends_on:
      - web_app
    networks:
      - ngoctq_my-network 
  web_app:
    image: ngoctq/python-web-app-docker-test    
    ports:
      - "8000:8000"
    deploy:
      mode: global
    networks:
      - ngoctq_my-network
networks:
  ngoctq_my-network: